config/routes.rb
Rails.application.routes.draw do
  root "home#dashboard"
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :product
  MovementTypes = {add: 0, remove: 1}
  validates :quantity, presence: true, numericality: true

  def self.get_movement_types
    {
      'Agregar' => MovementTypes[:add],
      'Quitar' => MovementTypes[:remove]
    }
  end

  def movement_type_name
    return "Agregar" if movement_type == MovementTypes[:add]
    return "Quitar" if movement_type == MovementTypes[:remove]
    return "NA"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :reference, presence: true
  has_many :movements

  def quantity
    total = 0
    self.movements.each do |movement|
      if movement.movement_type == Movement::MovementTypes[:add]
        total += movement.quantity
      else
        total -= movement.quantity
      end
    end
    return total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def dashboard
    @latest_movements = Movement.last(10)
    # La versión SQL y la versión Rails de la misma consulta:
    # @top_products = Product.find_by_sql("SELECT p.* FROM products p INNER JOIN movements m ON p.id = m.product_id WHERE m.movement_type = #{Movement::MovementTypes[:add]} GROUP BY p.id ORDER BY SUM(m.quantity) DESC LIMIT 10")
    @top_products = Product.joins(:movements).where(movements: {movement_type: Movement::MovementTypes[:add]}).group(:id).order("SUM(movements.quantity) DESC").limit(10)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Listado de productos.xlsx"'
      }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Se ha creado el producto correctamente.'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el producto.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"Listado de movimientos - #{@product.id}.xlsx\""
      }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: 'Se actualizó el producto correctamente'
    else
      render :edit
    end
  end

  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(product_id: @product.id)
  end

  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: 'Se creó el movimiento correctamente'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el movimiento.'
      render :new_movement, status: :unprocessable_entity
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :reference)
  end

  def movement_params
    params.require(:movement).permit(:movement_type, :quantity, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="card" style="padding: 20px">
      <h1>Últimos 10 movimientos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Producto</th>
            <th>Tipo</th>
            <th>Cantidad</th>
            <th>Fecha</th>
          </tr>
        </thead>
        <tbody>
          <% @latest_movements.each do |movement| %>
          <tr>
            <td><%= movement.product.name %></td>
            <td><%= movement.movement_type_name %></td>
            <td><%= movement.quantity %></td>
            <td><%= movement.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-lg-6">
    <div class="card" style="padding: 20px">
      <h1>Top 5 productos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Producto</th>
            <th>Referencia</th>
            <th>Cantidad</th>
          </tr>
        </thead>
        <tbody>
          <% @top_products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.reference %></td>
            <td><%= product.quantity %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi Bodega</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body id="page-top">
    <div id="wrapper">
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
          </div>
          <div class="sidebar-brand-text mx-3">Mi Bodega</div>
        </a>
        <hr class="sidebar-divider my-0">
        <li class="nav-item">
          <a class="nav-link" href="/">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span>
          </a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <li class="nav-item">
          <a class="nav-link" href="<%= products_path %>">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Productos</span>
          </a>
        </li>
      </ul>
      <!-- End of Sidebar -->
      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
              <i class="fa fa-bars"></i>
            </button>
          </nav>
          <!-- End of Topbar -->
          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- Page Heading -->
            <%= yield %>
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2020</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @product do |f| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger">
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control", placeholder: 'Caja' %>
        </div>
        <div class="form-group">
          <%= f.label :reference, "Referencia" %>
          <%= f.text_field :reference, class: "form-control", placeholder: 'CJ001' %>
        </div>
        <div class="form-group">
          <%= f.label :description, "Descripción" %>
          <%= f.text_area :description, class: "form-control", placeholder: 'Aqui la descripción del producto' %>
        </div>
        <div class="form-group">
          <%= f.submit "Enviar", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.erb
<h1>Editar producto existente</h1>
<a class="btn btn-primary" href="<%= product_path(@product) %>">Regresar al producto</a>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear Producto</span>
</a>
<a href="<%= products_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Exportar a Excel</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Referencia</th>
      <th>Cantidad</th>
      <th>Acciones</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.reference %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to "Detalles", product_path(product), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Crear nuevo producto</h1>
<a class="btn btn-primary" href="<%= products_path %>">Regresar al listado de productos</a>
<%= render 'form' %>

app/views/products/new_movement.html.erb
<h1>Crear movimiento</h1>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <table class="table">
        <tr>
          <td><b>Nombre:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Referencia:</b></td>
          <td><%= @product.reference %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row mt-5">
  <div class="col-lg-12">
    <div class="card p-5">
      <%= form_with model: @movement, url: create_movement_product_path(@product) do |f| %>
      <% if @movement.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @movement.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :movement_type, "Tipo de movimiento" %>
        <%= f.select :movement_type, options_for_select(Movement.get_movement_types,@movement.movement_type), {}, {class: 'form-control'}  %>
      </div>
      <div class="form-group">
        <%= f.label :quantity, "Cantidad" %>
        <%= f.number_field :quantity, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :comment, "Comentario" %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Enviar", class: 'btn btn-primary' %>
        <%= link_to "Cancelar", product_path(@product), class: 'btn btn-danger' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del producto</h1>
    <%= link_to "Regresar al listado de productos", products_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Crear movimiento", new_movement_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Descargar movimientos", product_path(@product, format: :xlsx), class: 'btn btn-success' %>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombre del producto:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Referencia:</b></td>
          <td><%= @product.reference %></td>
        </tr>
        <tr>
          <td><b>Cantidad actual:</b></td>
          <td><%= @product.quantity %></td>
        </tr>
        <tr>
          <td><b>Descripción:</b></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @product.created_at %></td>
        </tr>
        <tr>
          <td><b>Fecha de actualización:</b></td>
          <td><%= @product.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>
<div class="row" style="margin-top: 20px">
  <div class="col-lg-12">
    <div class="card" style="padding: 20px; ">
      <h1>Movimientos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Tipo</th>
            <th>Cantidad</th>
            <th>Comentario</th>
            <th>Fecha</th>
          </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement| %>
          <tr>
            <td><%= movement.movement_type_name %></td>
            <td><%= movement.quantity %></td>
            <td><%= movement.comment %></td>
            <td><%= movement.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>